CREATE TABLE IF NOT EXISTS users(
 id BIGSERIAL PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(255) UNIQUE,password_hash TEXT,
 role VARCHAR(20) NOT NULL DEFAULT 'user' CHECK(role IN('user','editor','admin','owner')),
 provider VARCHAR(30) DEFAULT 'email',provider_user_id VARCHAR(255),avatar_url TEXT,
 created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS categories(id BIGSERIAL PRIMARY KEY,name VARCHAR(100) UNIQUE NOT NULL,slug VARCHAR(120) UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS locations(id BIGSERIAL PRIMARY KEY,name VARCHAR(200) NOT NULL,address TEXT);
CREATE TABLE IF NOT EXISTS events(id BIGSERIAL PRIMARY KEY,title VARCHAR(255) NOT NULL,slug VARCHAR(280) UNIQUE,description TEXT,start_at TIMESTAMPTZ,end_at TIMESTAMPTZ,display_date VARCHAR(120),display_place VARCHAR(255),cover_position_x INT DEFAULT 50,cover_position_y INT DEFAULT 50,location_id BIGINT REFERENCES locations(id) ON DELETE SET NULL,category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,official_url TEXT,status VARCHAR(20) DEFAULT 'published',cover_image_url TEXT,created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS event_images(id BIGSERIAL PRIMARY KEY,event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,image_url TEXT NOT NULL,caption TEXT,sort_order INT DEFAULT 0,gallery_section VARCHAR(30) DEFAULT 'event');
CREATE TABLE IF NOT EXISTS event_attendance(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,status VARCHAR(20) NOT NULL CHECK(status IN('attended','planned','not_attended')),created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW(),UNIQUE(user_id,event_id));
CREATE TABLE IF NOT EXISTS experiences(id BIGSERIAL PRIMARY KEY,event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,title VARCHAR(255) NOT NULL,content TEXT NOT NULL,experience_type VARCHAR(20) DEFAULT 'community',published BOOLEAN DEFAULT TRUE,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS experience_images(id BIGSERIAL PRIMARY KEY,experience_id BIGINT REFERENCES experiences(id) ON DELETE CASCADE,image_url TEXT NOT NULL,caption TEXT,sort_order INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS comments(id BIGSERIAL PRIMARY KEY,event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,content TEXT NOT NULL,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS page_views(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,event_id BIGINT REFERENCES events(id) ON DELETE CASCADE,path TEXT,referrer TEXT,user_agent TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS login_logs(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,provider VARCHAR(30),success BOOLEAN DEFAULT FALSE,user_agent TEXT,created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS admin_audit_logs(id BIGSERIAL PRIMARY KEY,admin_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,action VARCHAR(50) NOT NULL,entity_type VARCHAR(50) NOT NULL,entity_id BIGINT,details JSONB,created_at TIMESTAMPTZ DEFAULT NOW());
INSERT INTO categories(name,slug) VALUES('Technology','technology'),('Gaming','gaming'),('Food & Beverage','food-beverage'),('Music','music'),('Lifestyle','lifestyle'),('Sport','sport') ON CONFLICT DO NOTHING;
